---
- name:    Download PHPUnit
  sudo:    no
  command: wget https://phar.phpunit.de/phpunit-6.0.phar

- name:    Add executable permissions to PHPUnit
  sudo:    no
  command: chmod +x phpunit-6.0.phar

- name:    Move PHPunit to /usr/local/bin
  sudo:    yes
  command: mv phpunit-6.0.phar /usr/local/bin/phpunit
