---
- name: Install Nginx
  sudo: yes
  yum: name=nginx state=present

- name: Change default nginx site
  sudo: yes
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
